# Generated by Django 4.0.3 on 2022-07-05 20:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_room_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='genre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(default=api.models.generate_uniquecode, max_length=8, unique=True),
        ),
    ]
