# Generated by Django 4.0.3 on 2022-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_place_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='taste',
            field=models.JSONField(default=dict),
        ),
    ]
