# Generated by Django 4.0.3 on 2022-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_place_name_alter_place_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='taste',
            field=models.JSONField(default={}),
        ),
    ]
