# Generated by Django 4.0.3 on 2022-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_place_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='base',
            field=models.CharField(default='', max_length=500),
        ),
    ]
