# Generated by Django 4.0.3 on 2022-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_place_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
